function laptopSVG(p){
 const rad=Math.PI/180,rx=p.pitch_deg*rad,ry=p.roll_deg*rad,rz=p.yaw_deg*rad,el=28*rad;
 function project(v){let[x,y,z]=v;[y,z]=[y*Math.cos(rx)-z*Math.sin(rx),y*Math.sin(rx)+z*Math.cos(rx)];[x,z]=[x*Math.cos(ry)+z*Math.sin(ry),-x*Math.sin(ry)+z*Math.cos(ry)];[x,y]=[x*Math.cos(rz)-y*Math.sin(rz),x*Math.sin(rz)+y*Math.cos(rz)];return [210+x*750,120+(y*Math.sin(el)-z*Math.cos(el))*750];}
 const base=[[-.1563,-.1106,0],[.1563,-.1106,0],[.1563,.1106,0],[-.1563,.1106,0]];
 const a=p.lid_deg*rad,back=[-.1563,.1106,.0155],tip=[-.1563,.1106-.203*Math.cos(a),.0155+.203*Math.sin(a)];
 const lid=[back,[.1563,back[1],back[2]],[.1563,tip[1],tip[2]],tip];
 const poly=(vs,c)=>'<polygon points="'+vs.map(project).map(v=>v.map(x=>x.toFixed(2)).join(',')).join(' ')+'" fill="'+c+'" stroke="#E1DED7" stroke-width="1.5"/>';
 return '<svg width="420" height="240" viewBox="0 0 420 240" xmlns="http://www.w3.org/2000/svg">'+poly(base,'#C9CBCE')+poly(lid,p.lid_deg>10?'#161719':'#B3B6BB')+'</svg>';
}
const intro=panel('10 / Scroll choreography','Six authored moves · supplements existing board 48:5573 with continuous angles and metric poses');
txt(intro,'Each transition: hold 0–10%, departure at 10%, lift at 30%, midpoint at 50%, approach at 70%, land at 90%, hold 90–100%. Reverse by evaluating the same progress backwards. Ease each segment with smoothstep; mesh scale remains 1.',23);
txt(intro,'Angles below are unwrapped degrees: pitch = Blender X, roll = Y, yaw = Z. The old board’s Y values represented yaw and its Z values represented roll. Complete turns retain ±360° at the boundaries rather than collapsing to 0°.',23);
txt(intro,'Metric positions are design coordinates for the feet-contact anchor. Camera seed: target = anchor + (0,0,0.08 m), camera = target + (0,-1.8,0.905 m), 50 mm lens / 36 mm sensor, roll 0°. Fit final cameras against the scene landmarks during the Blender pass; these are not measured render matches.',23,2272,'D8AF79');
const panels=[];
for(const t of MOTION.transitions){const p=panel(String(10+t.id).padStart(2,'0')+' / '+t.from+' → '+t.to,t.intent+' · source '+t.source_node);const row=stack(p,'Five poses','HORIZONTAL',18);for(const pose of t.poses.slice(1,-1)){const card=stack(row,pose.phase);card.resize(440,100);card.primaryAxisSizingMode='AUTO';fill(card,'0B0C0D','color/forest');card.paddingTop=card.paddingBottom=card.paddingLeft=card.paddingRight=12;txt(card,Math.round(pose.p*100)+'% / '+pose.phase,26,416,'D8AF79','Medium');const svg=track(figma.createNodeFromSvg(laptopSVG(pose)));card.appendChild(svg);for(const n of svg.findAll(()=>true))made.push(n.id);txt(card,'Pitch '+pose.pitch_deg+'°\nYaw '+pose.yaw_deg+'°\nRoll '+pose.roll_deg+'°\nLid '+pose.lid_deg+'°',24,416);txt(card,'XYZ m\n'+pose.position_m.join(' / ')+'\nFrame target px\n'+pose.subject_target_px.join(' / '),20,416,'A49B8F');}
txt(p,'Station visibility (from → to): 100/0 → 45/0 → 0/0 → 0/45 → 0/100. Source-station props remain fixed; only the single hero laptop travels. All adjacent boundary transforms and cameras agree.',22);panels.push(p.id);}
const paper=panel('17 / Paper feed + bird’s-eye','Deterministic reference states · portrait Letter page · aligned to local -Y');
const pr=stack(paper,'Feed states','HORIZONTAL',48);for(const [name,amount]of[['Hidden',0],['Emerging',.4],['Printed',1]]){const c=stack(pr,name);txt(c,name,28,700,'F1E9DC','Medium');const art=box(c,'Printer / '+name,700,520,'0B0C0D');rect(art,'Desk',25,15,650,490,'292721',14);const pc=await figma.getNodeByIdAsync('55:7252');await fonts(pc);const printer=inst(pc,art,.48);printer.x=270;printer.y=-35;const page=await figma.getNodeByIdAsync('113:11146');const sheet=inst(page,art,.3);sheet.x=330;sheet.y=164;if(amount===0)sheet.visible=false;else{const mask=box(art,'Visible paper below slot',194.4,251.58*amount,undefined,330,164);mask.clipsContent=true;mask.appendChild(sheet);sheet.x=0;sheet.y=0;}rect(art,'Output slot',322,155,210,8,'080808',3);}
txt(paper,'Leading edge Y: +210 mm hidden → +19.7 mm at slot → -92.1 mm at 40% exposure → -259.7 mm final. Sheet plane Z 742 mm. Final top edge +19.7 mm; no lateral movement or scale change.',23);
txt(paper,'Resume top-down: orthographic width 450 mm, target at page centre (230,-120,742 mm). Contact top-down: width 480 mm, target notebook (110,-160,748 mm). Camera ends at elevation 90° with roll 0°. Hold endpoints 10%; reuse the same reversible easing.',23);
await(await figma.getNodeByIdAsync(panels[0])).screenshot();
return {createdNodeIdsByPrefix:packedIds(),intro:intro.id,panels,paper:paper.id,poseCount:30,transitionCount:6};
