const changed=[];
const mp=['118:12514','118:12554','118:12594','118:12634','118:12674','118:12714'];
for(let i=0;i<mp.length;i++){const p=await figma.getNodeByIdAsync(mp[i]);await fonts(p);const row=p.children.find(c=>c.name==='Five poses');for(let j=0;j<5;j++){const card=row.children[j];const t=card.children.find(n=>n.type==='TEXT'&&n.characters.startsWith('XYZ m'));const target=(i===1&&j===4)||(i===2&&j===0)?'403.2 / 480':'720 / 480';t.characters=t.characters.replace(/Frame target px\n[\s\S]*/,'Frame target px\n'+target);changed.push(t.id);}}
const mi=await figma.getNodeByIdAsync('118:12508');const tx=txt(mi,'FRAMING UPDATE / Keep the travelling MacBook centred at 50% / 50% and larger: fit within 56% frame width and 64% height. Formula SAE alone settles to X 28% for car clearance, returning to centre by lift. Apply camera framing, never animate physical mesh scale. Full-station overviews are separate composition references.',25,2272,'D8AF79','Medium');
const mobile=panel('18 / Mobile + reduced motion','Same assets and materials · static or shortened camera alternatives');
const mr=stack(mobile,'Reference frames','HORIZONTAL',48);const ms=[];
for(const [id,name]of[['15:878','Mobile / Resume'],['15:1041','Mobile / Contact bird’s-eye'],['16:961','Reduced / Resume'],['16:1009','Reduced / Contact']]){const c=stack(mr,name);txt(c,name,25,515,'F1E9DC','Medium');const s=await scene(id,c,name,515);ms.push(s.id);}
txt(mobile,'Mobile: preserve a centred hero during travel and use tighter camera crops. Keep essential labels at ≥16 px in the eventual viewport. Reduced motion: display the landed pose; optional 150 ms dissolve only. Disable spins, barrel rolls and paper movement; show the printed résumé. Notebook links remain readable in the bird’s-eye reference.',23);
const proto=panel('19 / Reference walkthrough','Click through the checkpoints and final close-ups in Present mode');
txt(proto,'Start at 01 / Intro (4:600). Click the canvas to step through Hack → Hack close → Formula SAE → Ultra → Ultra close → Projects → Projects close → Resume → Resume top → Contact → Contact top. Drag interactions remain available. This is a review prototype; the scroll-driven 3D motion is specified in the storyboards and manifest.',23);
const flow=['4:600','4:635','54:6828','4:670','4:705','54:6950','4:740','54:7071','4:775','55:7271','4:810','13:2882'];
const checks=[];for(let i=0;i<flow.length;i++){const n=await figma.getNodeByIdAsync(flow[i]);const existing=n.reactions.filter(r=>r.trigger.type!=='ON_CLICK');await n.setReactionsAsync([...existing,{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:flow[(i+1)%flow.length],navigation:'NAVIGATE',transition:{type:'DISSOLVE',easing:{type:'EASE_IN_AND_OUT'},duration:.15}}]}]);changed.push(n.id);checks.push({id:n.id,clickTo:n.reactions.find(r=>r.trigger.type==='ON_CLICK').actions[0].destinationId});}
const section=await figma.getNodeByIdAsync('111:11081');section.resizeWithoutConstraints(5600,Math.ceil(board.height+200));changed.push(section.id);
// Make links on source references explicit without adding copy inside actual portfolio scenes.
const links=txt(proto,'Open existing motion board 48:5573  •  Review assets in this section 111:11081  •  Export masters in 111:11085',23);links.setRangeHyperlink(0,links.characters.indexOf('  •'),{type:'NODE',value:'48:5573'});changed.push(links.id);
await(await figma.getNodeByIdAsync('112:11095')).screenshot();await(await figma.getNodeByIdAsync('112:11127')).screenshot();await(await figma.getNodeByIdAsync('117:12528')).screenshot();await(await figma.getNodeByIdAsync('118:12754')).screenshot();
return {createdNodeIdsByPrefix:packedIds(),mutatedNodeIds:changed,mobilePanels:ms,prototypeLinks:checks,sectionSize:[section.width,section.height],reviewSize:[board.width,board.height],reviewPanels:board.children.filter(c=>c.type==='FRAME').map(c=>({id:c.id,name:c.name,w:c.width,h:c.height}))};
