const created=[];const overlay=await figma.getNodeByIdAsync('2:23');
const serif={family:'Cormorant Garamond',style:'Light'},regular={family:'Cormorant Garamond',style:'Regular'},mono={family:'IBM Plex Mono',style:'Regular'};
await Promise.all([serif,regular,mono].map(f=>figma.loadFontAsync(f)));
const vars=await figma.variables.getLocalVariablesAsync(), collection=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:2:2');
const paint=name=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',vars.find(v=>v.name===name));
const measures={};for(const [name,value,scopes]of [['spacing/pill-x',16,['GAP']],['spacing/pill-y',6,['GAP']],['radius/pill',99,['CORNER_RADIUS']],['spacing/nav',30,['GAP']]]){const v=figma.variables.createVariable(name,collection,'FLOAT');v.scopes=scopes;v.setValueForMode(collection.defaultModeId,value);v.setVariableCodeSyntax('WEB','--'+name.replaceAll('/','-'));measures[name]=v;}
function text(p,name,s,size,font=regular,col='text/cream',tracking=0){const t=figma.createText();t.name=name;t.fontName=font;t.fontSize=size;t.characters=s;t.lineHeight={unit:'PERCENT',value:100};t.letterSpacing={unit:'PERCENT',value:tracking};t.fills=[paint(col)];p.appendChild(t);created.push(t.id);return t;}
function group(p,name,dir='HORIZONTAL'){const g=figma.createAutoLayout(dir);g.name=name;g.fills=[];p.appendChild(g);created.push(g.id);return g;}
const header=group(overlay,'Header');header.resize(1340,28);header.primaryAxisSizingMode='FIXED';header.counterAxisSizingMode='FIXED';header.primaryAxisAlignItems='SPACE_BETWEEN';header.counterAxisAlignItems='CENTER';header.x=50;header.y=24;
text(header,'Wordmark','DAX MANUEL',14,mono,'text/cream',40);
const nav=group(header,'Primary navigation');nav.setBoundVariable('itemSpacing',measures['spacing/nav']);for(const label of ['Projects','About','Résumé','Contact'])text(nav,label,label,17);
const headline=text(overlay,'Hero headline','Pick something.\nExplore my work.',56,serif);headline.x=50;headline.y=105;headline.lineHeight={unit:'PERCENT',value:100};
const pill=figma.createComponent();pill.name='Object callout';pill.description='Projected object label. One live 3D anchor, accessible button, warm cream surface.';pill.x=5732;pill.y=100;pill.layoutMode='HORIZONTAL';pill.primaryAxisSizingMode='AUTO';pill.counterAxisSizingMode='AUTO';pill.fills=[paint('pill/bg')];for(const k of ['paddingLeft','paddingRight'])pill.setBoundVariable(k,measures['spacing/pill-x']);for(const k of ['paddingTop','paddingBottom'])pill.setBoundVariable(k,measures['spacing/pill-y']);pill.setBoundVariable('cornerRadius',measures['radius/pill']);created.push(pill.id);
const style=figma.createTextStyle();style.name='Object label / mono';style.fontName=mono;style.fontSize=12;style.lineHeight={unit:'PERCENT',value:100};
const label=text(pill,'Label','Experience',12,mono,'pill/text');label.textStyleId=style.id;const labelKey=pill.addComponentProperty('Label','TEXT','Experience');label.componentPropertyReferences={characters:labelKey};
const points=[['Experience',938,86,911,125],['Formula SAE',234,404,208,448],['Hack Atlantic',676,657,654,642],['Résumé',1181,429,1154,474],['Contact',1327,706,1301,685]];
for(const [s,x,y,ax,ay]of points){const n=pill.createInstance();n.setProperties({[labelKey]:s});overlay.appendChild(n);n.x=x;n.y=y;created.push(n.id,...n.findAll().map(c=>c.id));const minX=Math.min(ax,x),minY=Math.min(ay,y+12),w=Math.abs(x-ax)+1,h=Math.abs(y+12-ay)+1;const path=figma.createNodeFromSvg(`<svg xmlns="http://www.w3.org/2000/svg" width="${w+8}" height="${h+8}" viewBox="0 0 ${w+8} ${h+8}"><path d="M${ax-minX+4} ${ay-minY+4}L${x-minX-7+4} ${y+12-minY+4}H${x-minX+4}" fill="none" stroke="#ece6da" stroke-width="1"/><circle cx="${ax-minX+4}" cy="${ay-minY+4}" r="3.3" fill="#ece6da"/></svg>`);overlay.appendChild(path);path.name=s+' leader';path.x=minX-4;path.y=minY-4;created.push(path.id,...path.findAll().map(c=>c.id));}
const footer=group(overlay,'Choose an object','VERTICAL');footer.counterAxisAlignItems='CENTER';footer.itemSpacing=16;text(footer,'Instruction','CHOOSE AN OBJECT TO BEGIN',10,mono,'text/cream',25);
const tour=group(footer,'Take the tour');tour.paddingLeft=22;tour.paddingRight=22;tour.paddingTop=9;tour.paddingBottom=9;tour.cornerRadius=99;tour.strokes=[paint('text/cream')];tour.strokeWeight=1;text(tour,'Tour link','Take the tour  →',16);footer.x=720-footer.width/2;footer.y=884;
const nodes=overlay.findAll();const counts={};for(const n of nodes)counts[n.type]=(counts[n.type]||0)+1;
return {createdNodeIds:created,mutatedNodeIds:[overlay.id],componentId:pill.id,labelProperty:labelKey,overlayId:overlay.id,counts,fonts:[...new Set(nodes.filter(n=>n.type==='TEXT').map(n=>n.fontName.family))],imageNodes:nodes.filter(n=>'fills'in n&&Array.isArray(n.fills)&&n.fills.some(p=>p.type==='IMAGE')).map(n=>n.id),variables:Object.fromEntries(Object.entries(measures).map(([k,v])=>[k,v.id]))};
