import './workspace.css';
import {contactLinks} from './contact-book';
import resumeCopy from './resume-copy.json';
import {installScrollBack} from './scroll-back';
import {createUltraContent} from './ultra-screen';
import {createHackAtlanticSection} from './hack-atlantic';
import {FSAE_PROJECTS} from './fsae-projects';
import {immersiveDestinations} from './surface-focus';
import type {WorkspaceScene} from './workspace-scene';
const host=document.querySelector<HTMLDivElement>('#workspace')!;const base=import.meta.env.BASE_URL;
const resumePdf=base+'documents/dax-manuel-resume.pdf';
const choices=[['ultra-maritime','Experience'],['formula-sae','UNB Formula Racing'],['hack-atlantic','Hack Atlantic'],['resume','Résumé'],['contact','Contact']]as const;
host.innerHTML=`<a class="skip-desk" href="#projects">Skip to project list</a><canvas class="desk-canvas" aria-label="Interactive desk. Use the labeled buttons to explore Dax’s work."></canvas><div class="desk-grain" aria-hidden="true"></div><div class="editorial"><h1 class="desk-headline">Dax<br>Manuel</h1><div class="desk-callouts">${choices.map(([id,label])=>`<div class="callout" data-id="${id}"><img src="${base}assets/scene-realism/leaders/${['ultra-maritime','projects'].includes(id)?'experience':id}.svg" alt=""><button type="button" data-open="${id}" aria-label="Explore ${label}">${label}</button></div>`).join('')}</div><nav class="mobile-objects" aria-label="Explore desk objects">${choices.map(([id,label])=>`<button type="button" data-open="${id}">${label}</button>`).join('')}</nav></div><div class="desk-loader" role="status" aria-live="polite"><p>Loading…</p><progress max="100" value="0" aria-label="Loading workspace"></progress></div><dialog class="desk-dialog" aria-label="Portfolio detail"><button class="desk-close" type="button" aria-label="Close detail and return to desk">Close ✕</button><div class="desk-content"></div><svg class="racing-leader" aria-hidden="true"><path/><circle r="4"/></svg><nav class="phonebook-links" aria-label="Contact links written in the phonebook" hidden>${contactLinks.map(link=>`<a data-contact="${link.id}" href="${link.href}" ${link.href.startsWith('https:')?'target="_blank" rel="noopener noreferrer"':''} aria-label="${link.label}"><span class="visually-hidden">${link.label}</span></a>`).join('')}</nav><a class="printer-key-hit" href="${resumePdf}" download="Dax-Manuel-Resume.pdf" aria-label="Download résumé PDF" hidden><span class="visually-hidden">Download résumé PDF</span></a><nav class="notebook-pages" aria-label="Notebook pages"><button type="button" data-page="previous" aria-label="Previous notebook page">← Previous</button><output aria-live="polite">1 / 3</output><button type="button" data-page="next" aria-label="Next notebook page">Next →</button></nav></dialog>`;
const canvas=host.querySelector<HTMLCanvasElement>('canvas')!,loader=host.querySelector<HTMLDivElement>('.desk-loader')!,dialog=host.querySelector<HTMLDialogElement>('dialog')!,content=host.querySelector<HTMLDivElement>('.desk-content')!,callouts=[...host.querySelectorAll<HTMLElement>('.callout')];
const keyLink=host.querySelector<HTMLAnchorElement>('.printer-key-hit')!;
let keyHover=false,keyFocus=false;
for(const [event,value]of [['pointerenter',true],['pointerleave',false]]as const)keyLink.addEventListener(event,()=>{keyHover=value;scene?.setPrinterKeyState(keyHover,keyFocus);});
keyLink.addEventListener('focus',()=>{keyFocus=true;scene?.setPrinterKeyState(keyHover,true);});keyLink.addEventListener('blur',()=>{keyFocus=false;scene?.setPrinterKeyState(keyHover,false);});
keyLink.addEventListener('click',()=>scene?.pressPrinterKey());
keyLink.addEventListener('pointercancel',()=>{keyHover=false;scene?.setPrinterKeyState(false,keyFocus);});
const scrollBack=installScrollBack(dialog,content,()=>close(),{
 target:event=>{if(!scene?.ready||selected)return '';const element=event.target instanceof Element?event.target:null;const label=element?.closest<HTMLElement>('[data-open]');if(label)return label.dataset.open??'';return element===canvas?scene.pickAt(event):'';},
 busy:()=>!scene?.ready||scene.transitioning,
 open:id=>{open(id);}
});
let scene:WorkspaceScene|undefined,selected='',lastQa=0;let returnFocus:HTMLElement|null=null;
const qa=import.meta.env.DEV&&new URLSearchParams(location.search).has('qa');let output:HTMLOutputElement|undefined;
if(qa){output=document.createElement('output');output.className='qa-output';output.setAttribute('aria-label','Scene diagnostics');host.append(output);}
if(import.meta.env.DEV&&new URLSearchParams(location.search).has('overlay')){const img=new Image();img.src=base+'assets/scene-realism/reference.png';img.className='reference-overlay';img.alt='';host.append(img);}
function projectLinks(){return `<nav aria-label="Projects"><a href="#hack-atlantic">Hack Atlantic ↗</a><a href="#formula-sae">UNB Formula Racing ↗</a></nav>`;}
function updateNotebookControls(){const page=scene?.notebookPage??0;host.querySelector<HTMLOutputElement>('.notebook-pages output')!.value=`${page+1} / 3`;host.querySelector<HTMLButtonElement>('[data-page=previous]')!.disabled=page===0;host.querySelector<HTMLButtonElement>('[data-page=next]')!.disabled=page===2;}
for(const button of host.querySelectorAll<HTMLButtonElement>('[data-page]'))button.addEventListener('click',()=>{scene?.setNotebookPage((scene.notebookPage)+(button.dataset.page==='next'?1:-1));updateNotebookControls();if(button.disabled)host.querySelector<HTMLButtonElement>(button.dataset.page==='next'?'[data-page=previous]':'[data-page=next]')!.focus({preventScroll:true});});
function populate(id:string){content.replaceChildren();
 if(id==='ultra-maritime')content.append(createUltraContent());
 else if(id==='hack-atlantic')content.append(createHackAtlanticSection());
 else if(id==='formula-sae'){const p=FSAE_PROJECTS.data;content.innerHTML=`<p class="racing-eyebrow">UNB Formula Racing</p><h2>Founding Member &amp; Software Project Lead</h2><section>${p.description.map(t=>`<p>${t}</p>`).join('')}</section>`;}
 else if(id==='resume'){const title=document.createElement('h2');title.textContent='Résumé';const text=document.createElement('p');text.textContent=resumeCopy.text;content.append(title,text);if(!scene?.hasSurface(id)){const download=document.createElement('a');download.href=resumePdf;download.download='Dax-Manuel-Resume.pdf';download.textContent='Download PDF';content.append(download);}}
 else if(id==='contact'&&scene?.hasSurface(id)){content.innerHTML='<h2>Contact phonebook</h2><p>Choose a handwritten contact or social link.</p>'; }
 else if(id==='contact'){content.innerHTML=`<h2>Let’s make something.</h2><p><a href="mailto:mail@daxmanuel.com">mail@daxmanuel.com</a><br><a href="tel:+15068972218">506-897-2218</a></p><nav aria-label="Contact profiles"><a href="https://github.com/daxmanuel27" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/nikolasdaxmanuel" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://x.com/bydaxmanuel" target="_blank" rel="noopener noreferrer">X ↗</a></nav>`;}
 else if(id==='about'){content.innerHTML=`<h2>Dax Manuel</h2><p>Engineering, design and technology.</p><p>Founder of Hack Atlantic, Software Engineer Intern at Ultra Maritime, and Founding Member &amp; Software Project Lead at UNB Formula Racing.</p>${projectLinks()}<nav><a href="#ultra-maritime">Explore my experience →</a></nav>`;}
 else{content.innerHTML=`<h2>Projects</h2>${projectLinks()}`;}
}
function open(id:string,updateHistory=true){if(['fsae-pedal-sensor','fsae-data-logging','raspberry-pi'].includes(id))id='formula-sae';if(id==='accessible-contact')id='contact';if(['intro','', 'desk'].includes(id)){close(updateHistory);return;}if(!['ultra-maritime','hack-atlantic','formula-sae','fsae-data-logging','resume','contact','projects','about','raspberry-pi'].includes(id))return;
 scrollBack.reset();if(!dialog.open)returnFocus=document.activeElement as HTMLElement;content.removeAttribute('style');selected=id;const annotation=id==='formula-sae';const immersive=immersiveDestinations.has(id)||annotation;dialog.classList.toggle('racing-annotation',annotation);dialog.classList.toggle('immersive',immersive);dialog.classList.remove('arrived');dialog.dataset.destination=id;host.classList.toggle('in-destination',immersive);populate(id);dialog.classList.toggle('physical-surface',!!scene?.hasSurface(id)&&['resume','contact'].includes(id));host.querySelector<HTMLElement>('.phonebook-links')!.hidden=id!=='contact'||!scene?.hasSurface(id);host.querySelector<HTMLElement>('.printer-key-hit')!.hidden=true;updateNotebookControls();if(!dialog.open)dialog.showModal();const closeButton=host.querySelector<HTMLButtonElement>('.desk-close')!;closeButton.textContent=immersive?'← Back to desk':'Close ✕';closeButton.focus({preventScroll:true});if(immersive){const reveal=()=>{if(selected===id){dialog.classList.add('arrived');content.inert=false;}};content.inert=true;if(scene?.ready)scene.focus(id,reveal);else reveal();}else{content.inert=false;scene?.focus(id==='about'?'ultra-maritime':id,undefined,false);}dialog.scrollTop=0;content.scrollTop=0;host.querySelector<HTMLElement>('.desk-headline')!.hidden=true;host.querySelector<HTMLElement>('.desk-callouts')!.hidden=true;host.querySelector<HTMLElement>('.mobile-objects')!.hidden=true;if(updateHistory)history.pushState(null,'','#'+id);}
function close(updateHistory=true){host.querySelector<HTMLElement>('.printer-key-hit')!.hidden=true;scrollBack.reset();selected='';host.classList.remove('in-destination');dialog.classList.remove('arrived');content.inert=false;if(dialog.open)dialog.close();scene?.homeView();for(const selector of ['.desk-headline','.desk-callouts','.mobile-objects'])host.querySelector<HTMLElement>(selector)!.hidden=false;if(updateHistory)history.pushState(null,'',location.pathname+location.search);returnFocus?.focus({preventScroll:true});}
host.addEventListener('click',event=>{const target=event.target as HTMLElement;const button=target.closest<HTMLElement>('[data-open]');if(button){open(button.dataset.open!);}const link=target.closest<HTMLAnchorElement>('a[href^="#"]');if(link){event.preventDefault();open(link.hash.slice(1));}});
for(const button of host.querySelectorAll<HTMLElement>('[data-open]')){button.addEventListener('pointerenter',()=>scene?.highlight(button.dataset.open!));button.addEventListener('focus',()=>scene?.highlight(button.dataset.open!));button.addEventListener('blur',()=>scene?.highlight(selected||'hack-atlantic'));}
host.querySelector('.desk-close')!.addEventListener('click',()=>close());dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});

addEventListener('popstate',()=>{open(location.hash.slice(1),false);});addEventListener('hashchange',()=>{open(location.hash.slice(1),false);});
function frame(){
 if(dialog.classList.contains('racing-annotation')&&dialog.classList.contains('arrived')){const p=scene?.anchor('fsae-data-logging'),svg=host.querySelector<SVGSVGElement>('.racing-leader')!;svg.style.visibility=p?.visible?'visible':'hidden';if(p){const r=content.getBoundingClientRect(),x=r.right+18,y=r.top+52;svg.querySelector('path')!.setAttribute('d',`M ${x} ${y} H ${x+28} L ${p.x-22} ${p.y} H ${p.x}`);svg.querySelector('circle')!.setAttribute('cx',String(p.x));svg.querySelector('circle')!.setAttribute('cy',String(p.y));}}

 const keyLink=host.querySelector<HTMLAnchorElement>('.printer-key-hit')!,key=selected==='resume'?scene?.printerKeyRegion():null;keyLink.hidden=!key;if(key){keyLink.style.left=key.left+'px';keyLink.style.top=key.top+'px';keyLink.style.width=key.width+'px';keyLink.style.height=key.height+'px';}
 if(selected==='contact'){for(const r of scene?.contactRegions()??[]){const link=host.querySelector<HTMLAnchorElement>(`[data-contact="${r.id}"]`)!;link.hidden=!r.visible;link.style.left=r.left+'px';link.style.top=(r.top-Math.max(0,44-r.height)/2)+'px';link.style.width=r.width+'px';link.style.height=Math.max(44,r.height)+'px';}}
if(selected!=='projects'&&!dialog.classList.contains('physical-surface')&&!(selected==='ultra-maritime'&&scene?.notebookReady)&&immersiveDestinations.has(selected)&&dialog.classList.contains('arrived')){const r=scene?.surfaceRect(selected);if(r){content.style.left=r.left+'px';content.style.top=r.top+'px';content.style.width=r.width+'px';content.style.height=r.height+'px';}}for(const node of callouts){const p=scene?.anchor(node.dataset.id!);node.classList.toggle('ready',!!p?.visible);if(p){const x=p.x;node.style.transform=`translate(${x}px,${p.y}px)`;}}if(output&&performance.now()-lastQa>1000){output.value=JSON.stringify(scene?.diagnostics());lastQa=performance.now();}}
async function start(){try{const{WorkspaceScene}=await import('./workspace-scene');scene=new WorkspaceScene(canvas,id=>{open(id);},frame);await scene.load(n=>{loader.querySelector('progress')!.value=Math.round(n*100);});host.classList.toggle('notebook-artwork-ready',scene.notebookReady);loader.hidden=true;if(location.hash)open(location.hash.slice(1),false);}catch(error){console.error(error);loader.innerHTML='<p>The desk couldn’t load.</p><div class="desk-failure">You can still explore all the work using the navigation.</div><button type="button">Continue to projects</button>';loader.querySelector('button')!.onclick=()=>{loader.hidden=true;open('projects');};}}
void start();
