import './workspace.css';
import {ABOUT_ROLES,ABOUT_PHOTOS,ABOUT_INTRO} from './laptop-screen';
import {LABELS,labelContent,labelMarkup,updateLabels} from './workspace-labels';
import {createRecapContent} from './scroll-frame';
import {contactLinks} from './contact-book';
import resumeCopy from './resume-copy.json';
import {installScrollBack} from './scroll-back';
import {createUltraContent} from './ultra-screen';
import {FSAE_PROJECTS} from './fsae-projects';
import {immersiveDestinations} from './surface-focus';
import type {WorkspaceScene} from './workspace-scene';
const host=document.querySelector<HTMLDivElement>('#workspace')!;const base=import.meta.env.BASE_URL;
const resumePdf=base+'documents/dax-manuel-resume.pdf';
const choices=[...LABELS].sort((a,b)=>a.tabOrder-b.tabOrder).map(({id,label})=>[id,label] as const);
host.classList.add('is-loading');host.setAttribute('aria-busy','true');
host.innerHTML=`<a class="skip-desk" href="#projects">Skip to project list</a><canvas class="desk-canvas" aria-label="Interactive desk. Use the labeled buttons to explore Dax’s work."></canvas><div class="desk-grain" aria-hidden="true"></div><div class="editorial" inert><h1 class="desk-headline"><span>DAX</span><span>MANUEL</span></h1><div class="desk-callouts">${labelMarkup()}</div><nav class="mobile-objects" aria-label="Explore desk objects">${choices.map(([id,label])=>`<button type="button" data-open="${id}" aria-label="${label}">${labelContent(id,label)}</button>`).join('')}</nav></div><div class="desk-loader" role="status" aria-live="polite"><progress max="100" value="0" aria-label="Loading workspace"></progress></div><dialog class="desk-dialog" aria-label="Portfolio detail"><button class="desk-close" type="button" aria-label="Close detail and return to desk">Close ✕</button><div class="desk-content"></div><nav class="about-gallery-controls" aria-label="Photo gallery controls"><button type="button" data-gallery="previous" aria-label="Previous photos">←</button><button type="button" data-gallery="pause">Pause gallery</button><button type="button" data-gallery="next" aria-label="Next photos">→</button></nav><div class="fabric-controls" hidden><button class="fabric-hit" aria-label="Hack Atlantic fabric. Drag, scroll, or use arrow keys to read." type="button"></button><nav aria-label="Scroll frame controls"><button type="button" data-fabric="up" aria-label="Wind fabric upward">↑</button><span>Scroll or drag to read</span><button type="button" data-fabric="down" aria-label="Wind fabric downward">↓</button><button type="button" data-fabric="read">Read as text</button></nav></div><svg class="racing-leader" aria-hidden="true"><path/><circle r="4"/></svg><nav class="phonebook-links" aria-label="Contact links written in the phonebook" hidden>${contactLinks.map(link=>`<a data-contact="${link.id}" href="${link.href}" ${link.href.startsWith('https:')?'target="_blank" rel="noopener noreferrer"':''} aria-label="${link.label}"><span class="visually-hidden">${link.label}</span></a>`).join('')}</nav><a class="printer-key-hit" href="${resumePdf}" download="Dax-Manuel-Resume.pdf" aria-label="Download résumé PDF" hidden><span class="visually-hidden">Download résumé PDF</span></a><nav class="notebook-pages" aria-label="Notebook pages"><button type="button" data-page="previous" aria-label="Previous notebook page">← Previous</button><output aria-live="polite">1 / 3</output><button type="button" data-page="next" aria-label="Next notebook page">Next →</button></nav></dialog>`;
const canvas=host.querySelector<HTMLCanvasElement>('canvas')!,loader=host.querySelector<HTMLDivElement>('.desk-loader')!,dialog=host.querySelector<HTMLDialogElement>('dialog')!,content=host.querySelector<HTMLDivElement>('.desk-content')!,callouts=[...host.querySelectorAll<HTMLElement>('.callout')];
const keyLink=host.querySelector<HTMLAnchorElement>('.printer-key-hit')!;
let keyHover=false,keyFocus=false;
for(const [event,value]of [['pointerenter',true],['pointerleave',false]]as const)keyLink.addEventListener(event,()=>{keyHover=value;scene?.setPrinterKeyState(keyHover,keyFocus);});
keyLink.addEventListener('focus',()=>{keyFocus=true;scene?.setPrinterKeyState(keyHover,true);});keyLink.addEventListener('blur',()=>{keyFocus=false;scene?.setPrinterKeyState(keyHover,false);});
keyLink.addEventListener('click',()=>scene?.pressPrinterKey());
keyLink.addEventListener('pointercancel',()=>{keyHover=false;scene?.setPrinterKeyState(false,keyFocus);});
const scrollBack=installScrollBack(dialog,content,()=>close(),{
 ignore:event=>hackOverviewAt(event),
 atTop:()=>selected!=='hack-atlantic'||dialog.classList.contains('reading-fabric')||!!scene?.fabricAtTop,
 target:event=>{if(!scene?.ready||selected)return '';const element=event.target instanceof Element?event.target:null;const label=element?.closest<HTMLElement>('[data-open]');if(label)return label.dataset.open??'';return element===canvas?scene.pickAt(event):'';},
 busy:()=>!scene?.ready||scene.transitioning,
 open:id=>{open(id);}
});
let scene:WorkspaceScene|undefined,selected='',lastQa=0;let returnFocus:HTMLElement|null=null;
const qa=import.meta.env.DEV&&new URLSearchParams(location.search).has('qa');let output:HTMLOutputElement|undefined;
if(qa){output=document.createElement('output');output.className='qa-output';output.setAttribute('aria-label','Scene diagnostics');host.append(output);}
if(import.meta.env.DEV&&new URLSearchParams(location.search).has('overlay')){const img=new Image();img.src=base+'assets/scene-realism/reference.png';img.className='reference-overlay';img.alt='';host.append(img);}
function projectLinks(){return `<nav aria-label="Projects"><a href="#hack-atlantic">Hack Atlantic ↗</a><a href="#formula-sae">UNB Formula Racing ↗</a></nav>`;}
function updateNotebookControls(){const page=scene?.notebookPage??0;host.querySelector<HTMLOutputElement>('.notebook-pages output')!.value=`${page+1} / 3`;host.querySelector<HTMLButtonElement>('[data-page=previous]')!.disabled=page===0;host.querySelector<HTMLButtonElement>('[data-page=next]')!.disabled=page===2;}
for(const button of host.querySelectorAll<HTMLButtonElement>('[data-page]'))button.addEventListener('click',()=>{scene?.setNotebookPage((scene.notebookPage)+(button.dataset.page==='next'?1:-1));updateNotebookControls();if(button.disabled)host.querySelector<HTMLButtonElement>(button.dataset.page==='next'?'[data-page=previous]':'[data-page=next]')!.focus({preventScroll:true});});
function populate(id:string){content.replaceChildren();content.removeAttribute('aria-label');
 if(id==='ultra-maritime')content.append(createUltraContent());
 else if(id==='hack-atlantic')content.append(createRecapContent());
 else if(id==='formula-sae'){const p=FSAE_PROJECTS.data;content.innerHTML=`<p class="racing-eyebrow">UNB Formula Racing</p><h2>Founding Member &amp; Software Project Lead</h2><section>${p.description.map(t=>`<p>${t}</p>`).join('')}</section>`;}
 else if(id==='resume'){const title=document.createElement('h2');title.textContent='Résumé';const text=document.createElement('p');text.textContent=resumeCopy.text;content.append(title,text);if(!scene?.hasSurface(id)){const download=document.createElement('a');download.href=resumePdf;download.download='Dax-Manuel-Resume.pdf';download.textContent='Download PDF';content.append(download);}}
 else if(id==='contact'&&scene?.hasSurface(id)){content.innerHTML='<h2>Contact phonebook</h2><p>Choose a handwritten contact or social link.</p>'; }
 else if(id==='contact'){content.innerHTML=`<h2>Let’s make something.</h2><p><a href="mailto:mail@daxmanuel.com">mail@daxmanuel.com</a><br><a href="tel:+15068972218">506-897-2218</a></p><nav aria-label="Contact profiles"><a href="https://github.com/daxmanuel27" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/nikolasdaxmanuel" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://x.com/bydaxmanuel" target="_blank" rel="noopener noreferrer">X ↗</a></nav>`;}
 else if(id==='about'){content.setAttribute('aria-label','About Dax Manuel');const title=document.createElement('h2');title.textContent='About';content.append(title);const roles=document.createElement('p');roles.textContent=ABOUT_ROLES.join(', ');content.append(roles);const intro=document.createElement('p');intro.textContent=ABOUT_INTRO;content.append(intro);const gallery=document.createElement('p');gallery.textContent='Photo gallery: '+ABOUT_PHOTOS.join('; ')+', and a muted video.';content.append(gallery);}
 else{content.innerHTML=`<h2>Projects</h2>${projectLinks()}`;}
}
function open(id:string,updateHistory=true){if(['fsae-pedal-sensor','fsae-data-logging','raspberry-pi'].includes(id))id='formula-sae';if(id==='accessible-contact')id='contact';if(['intro','', 'desk'].includes(id)){close(updateHistory);return;}if(!['ultra-maritime','hack-atlantic','formula-sae','fsae-data-logging','resume','contact','projects','about','raspberry-pi'].includes(id))return;
 scrollBack.reset();if(!dialog.open)returnFocus=document.activeElement as HTMLElement;content.removeAttribute('style');selected=id;const annotation=id==='formula-sae';const immersive=immersiveDestinations.has(id)||annotation;dialog.classList.toggle('racing-annotation',annotation);dialog.classList.toggle('immersive',immersive);dialog.classList.remove('arrived');dialog.dataset.destination=id;dialog.classList.remove('reading-fabric');host.querySelector<HTMLElement>('.fabric-controls')!.hidden=id!=='hack-atlantic';host.classList.toggle('in-destination',immersive);populate(id);dialog.classList.toggle('physical-surface',!!scene?.hasSurface(id)&&['resume','contact','about'].includes(id));host.querySelector<HTMLElement>('.phonebook-links')!.hidden=id!=='contact'||!scene?.hasSurface(id);host.querySelector<HTMLElement>('.printer-key-hit')!.hidden=true;updateNotebookControls();if(!dialog.open)dialog.showModal();const closeButton=host.querySelector<HTMLButtonElement>('.desk-close')!;closeButton.textContent=immersive?'← Back to desk':'Close ✕';closeButton.focus({preventScroll:true});if(immersive){const reveal=()=>{if(selected===id){dialog.classList.add('arrived');content.inert=false;if(id==='hack-atlantic')host.querySelector<HTMLButtonElement>('.fabric-hit')!.focus({preventScroll:true});}};content.inert=true;if(scene?.ready)scene.focus(id,reveal);else reveal();}else{content.inert=false;scene?.focus(id,undefined,false);}dialog.scrollTop=0;content.scrollTop=0;host.querySelector<HTMLElement>('.desk-headline')!.hidden=true;host.querySelector<HTMLElement>('.desk-callouts')!.hidden=true;host.querySelector<HTMLElement>('.mobile-objects')!.hidden=true;if(updateHistory)history.pushState(null,'','#'+id);}
function close(updateHistory=true){enteringFabricGesture=false;host.querySelector<HTMLElement>('.fabric-controls')!.hidden=true;host.querySelector<HTMLElement>('.printer-key-hit')!.hidden=true;scrollBack.reset();selected='';host.classList.remove('in-destination');dialog.classList.remove('arrived');content.inert=false;if(dialog.open)dialog.close();scene?.homeView();for(const selector of ['.desk-headline','.desk-callouts','.mobile-objects'])host.querySelector<HTMLElement>(selector)!.hidden=false;if(updateHistory)history.pushState(null,'',location.pathname+location.search);returnFocus?.focus({preventScroll:true});}
host.addEventListener('click',event=>{const target=event.target as HTMLElement;const button=target.closest<HTMLElement>('[data-open]');if(button){open(button.dataset.open!);}const link=target.closest<HTMLAnchorElement>('a[href^="#"]');if(link){event.preventDefault();open(link.hash.slice(1));}});
for(const button of host.querySelectorAll<HTMLElement>('[data-open]')){button.addEventListener('pointerenter',()=>scene?.highlight(button.dataset.open!));button.addEventListener('focus',()=>scene?.highlight(button.dataset.open!));button.addEventListener('pointerleave',()=>scene?.highlight(selected||''));button.addEventListener('blur',()=>scene?.highlight(selected||''));}
host.querySelector('.desk-close')!.addEventListener('click',()=>close());dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog){if(selected==='hack-atlantic'||selected==='about'){const surface=scene?.surfaceRect(selected);if(!surface||e.clientX<surface.left||e.clientX>surface.left+surface.width||e.clientY<surface.top||e.clientY>surface.top+surface.height)close();return;}const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});

addEventListener('popstate',()=>{open(location.hash.slice(1),false);});addEventListener('hashchange',()=>{open(location.hash.slice(1),false);});
function frame(){
 if(dialog.classList.contains('racing-annotation')&&dialog.classList.contains('arrived')){const p=scene?.anchor('fsae-data-logging'),svg=host.querySelector<SVGSVGElement>('.racing-leader')!;svg.style.visibility=p?.visible?'visible':'hidden';if(p){const r=content.getBoundingClientRect(),x=r.right+18,y=r.top+52;svg.querySelector('path')!.setAttribute('d',`M ${x} ${y} H ${x+28} L ${p.x-22} ${p.y} H ${p.x}`);svg.querySelector('circle')!.setAttribute('cx',String(p.x));svg.querySelector('circle')!.setAttribute('cy',String(p.y));}}

 const keyLink=host.querySelector<HTMLAnchorElement>('.printer-key-hit')!,key=selected==='resume'?scene?.printerKeyRegion():null;keyLink.hidden=!key;if(key){keyLink.style.left=key.left+'px';keyLink.style.top=key.top+'px';keyLink.style.width=key.width+'px';keyLink.style.height=key.height+'px';}
 if(selected==='contact'){for(const r of scene?.contactRegions()??[]){const link=host.querySelector<HTMLAnchorElement>(`[data-contact="${r.id}"]`)!;link.hidden=!r.visible;link.style.left=r.left+'px';link.style.top=(r.top-Math.max(0,44-r.height)/2)+'px';link.style.width=r.width+'px';link.style.height=Math.max(44,r.height)+'px';}}
if(selected!=='hack-atlantic'&&selected!=='projects'&&!dialog.classList.contains('physical-surface')&&!(selected==='ultra-maritime'&&scene?.notebookReady)&&immersiveDestinations.has(selected)&&dialog.classList.contains('arrived')){const r=scene?.surfaceRect(selected);if(r){content.style.left=r.left+'px';content.style.top=r.top+'px';content.style.width=r.width+'px';content.style.height=r.height+'px';}}if(!selected&&innerWidth>=760)updateLabels(callouts,id=>scene?.anchor(id),scene?.objectRects()??[]);for(const node of callouts)node.classList.toggle('highlighted',node.dataset.id===scene?.hovered);if(selected==='hack-atlantic'){const r=scene?.surfaceRect(selected),hit=host.querySelector<HTMLElement>('.fabric-hit')!;if(r){Object.assign(hit.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});}}if(output&&performance.now()-lastQa>1000){output.value=JSON.stringify(scene?.diagnostics());lastQa=performance.now();}}
const fabricHit=host.querySelector<HTMLButtonElement>('.fabric-hit')!;
let drag:{y:number;pointerId:number;target:HTMLElement}|undefined;
function hackOverviewAt(e:MouseEvent){return !selected&&((e.target instanceof Element&&!!e.target.closest('[data-open="hack-atlantic"]'))||(e.target===canvas&&scene?.pickAt(e)==='hack-atlantic'));}
function fabricAt(e:MouseEvent){return selected==='hack-atlantic'&&dialog.classList.contains('arrived')&&e.target===fabricHit;}
let enteringFabricGesture=false,lastFabricWheel=-Infinity;
host.addEventListener('wheel',e=>{
 if(e.ctrlKey||e.metaKey||!e.deltaY||Math.abs(e.deltaX)>Math.abs(e.deltaY))return;
 const now=performance.now();
 if(hackOverviewAt(e)){
  e.preventDefault();if(!scene?.ready||scene.transitioning)return;
  enteringFabricGesture=true;lastFabricWheel=now;open('hack-atlantic');return;
 }
 if(selected!=='hack-atlantic')return;
 if(scene?.transitioning){e.preventDefault();lastFabricWheel=now;return;}
 // Consume the entry gesture's trackpad momentum; a new gesture reads the print.
 if(enteringFabricGesture){const fresh=now-lastFabricWheel>280;lastFabricWheel=now;if(!fresh){e.preventDefault();return;}enteringFabricGesture=false;}
 if(!fabricAt(e))return;
 e.preventDefault();scene?.scrollFabric(e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?innerHeight:1));host.classList.add('fabric-used');
},{passive:false});
for(const target of [canvas,fabricHit] as HTMLElement[]){
 target.addEventListener('pointerdown',e=>{if(!fabricAt(e))return;drag={y:e.clientY,pointerId:e.pointerId,target};target.style.touchAction='none';target.setPointerCapture(e.pointerId);});
 target.addEventListener('pointermove',e=>{if(!drag||drag.pointerId!==e.pointerId)return;scene?.scrollFabric((drag.y-e.clientY)*3);drag.y=e.clientY;});
 const release=(e:PointerEvent)=>{if(drag?.pointerId===e.pointerId){if(target.hasPointerCapture(e.pointerId))target.releasePointerCapture(e.pointerId);drag=undefined;target.style.touchAction='';}};target.addEventListener('pointerup',release);target.addEventListener('pointercancel',release);
}
fabricHit.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(e.key)){e.preventDefault();if(e.key==='Home'||e.key==='End')scene?.setFabric(e.key==='Home'?0:1);else scene?.scrollFabric((e.key==='ArrowUp'||e.key==='PageUp'?-1:1)*(e.key.startsWith('Arrow')?100:500));}});
for(const button of host.querySelectorAll<HTMLButtonElement>('[data-fabric]'))button.addEventListener('click',()=>{const action=button.dataset.fabric;if(action==='read'){dialog.classList.toggle('reading-fabric');button.textContent=dialog.classList.contains('reading-fabric')?'Back to fabric':'Read as text';}else scene?.scrollFabric(action==='up'?-300:300);});
function revealWorkspace(){loader.hidden=true;host.classList.remove('is-loading');host.setAttribute('aria-busy','false');host.querySelector<HTMLElement>('.editorial')!.inert=false;}
async function start(){try{const{WorkspaceScene}=await import('./workspace-scene');scene=new WorkspaceScene(canvas,id=>{open(id);},frame);await scene.load(n=>{loader.querySelector('progress')!.value=Math.round(n*100);});host.classList.toggle('notebook-artwork-ready',scene.notebookReady);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));revealWorkspace();if(location.hash)open(location.hash.slice(1),false);}catch(error){console.error(error);loader.innerHTML='<p>The desk couldn’t load.</p><div class="desk-failure">You can still explore all the work using the project list.</div><button type="button">Continue to projects</button>';loader.querySelector('button')!.onclick=()=>{revealWorkspace();open('projects');};}}
void start();
if(import.meta.env.DEV&&qa)Object.assign(window,{__roomQA:{snapshot:()=>scene?.diagnostics(),scene:()=>scene,open,close}});

for(const button of host.querySelectorAll<HTMLButtonElement>('[data-gallery]'))button.addEventListener('click',()=>{const action=button.dataset.gallery;const paused=action==='pause'?scene?.toggleAboutGallery():scene?.stepAboutGallery(action==='next'?1:-1);host.querySelector<HTMLButtonElement>('[data-gallery=pause]')!.textContent=paused?'Play gallery':'Pause gallery';});
